server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/comex
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.instance.prefer-ip-address=true
spring.application.name=produto-ms
eureka.client.serviceUrl.defaultZone=http://localhost:8083/eureka

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=4

spring.rabbitmq.listener.simple.retry.initial-interval=500
spring.rabbitmq.listener.simple.retry.multiplier=2
spring.rabbitmq.listener.simple.retry.max-interval=2500

token-validation.base-url=http://localhost:8084/usuario-ms

kafka.broker.host-and-port=localhost:9092